### ISSUE TITLE
Problem running app in IIS 

### ISSUE THREAD

**Issue by greibach** [dylanplecki/KeycloakOwinAuthentication#27]
When I try to run the app in IIS outside VS I am getting this error:

HTTP Error 404.0 - Not Found
The resource you are looking for has been removed, had its name changed, or is temporarily unavailable.
Requested URL	http://192.168.1.223:80/myApp/owin/security/keycloak/KeycloakAuthentication/callback
Physical Path	D:\Projects\Keycloak\KeycloakOwinAuthentication-master\src\SampleKeycloakApp\owin\security\keycloak\KeycloakAuthentication\callback

Where myApp is the virtual folder in IIS. The sample works fine running from Visual Studio.
Any idea what I am doing wrong?

Thanks

**Comment by greibach** [comment]
Ok, setting the **VirtualDirectory** property in KeycloakAuthenticationOptions seems to work for me

**Comment by akiladevv** [comment]
Hi,
Can you please send me the sample app for keycloakAuthentication (in Visual Studio)

Thank you
