### ISSUE TITLE
Logout Error - Request.GetOwinContext().Authentication.SignOut()

### ISSUE THREAD

**Issue by ntheile** [dylanplecki/KeycloakOwinAuthentication#29]
When trying to log out via Request.GetOwinContext().Authentication.SignOut(),  I get the following error: 

**Value cannot be null.
Parameter name: uriString
[ArgumentNullException: Value cannot be null.
Parameter name: uriString]
   System.Uri..ctor(String uriString) +6766781
   Owin.Security.Keycloak.Middleware.<LogoutRedirectAsync>d__10.MoveNext() +120
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   System.Runtime.CompilerServices.TaskAwaiter.GetResult() +26
   Owin.Security.Keycloak.Middleware.<ApplyResponseGrantAsync>d__2.MoveNext() +243
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
...**

A quick workaround is to delete the aspnet cookie and hit the OIDC logout url:

<pre>
if (Request.Cookies[".AspNet.kcook"] != null) { 
        HttpCookie myCookie = new HttpCookie(".AspNet.kcook");
        myCookie.Expires = DateTime.Now.AddDays(-1d);
        Response.Cookies.Add(myCookie);
}
Response.Redirect("https://idmendpoint.com/auth/realms/MyRealm/protocol/openid-connect/logout?redirect_uri=https%3A%2F%2Flocalhost%3A44303");
</pre>

**Comment by greibach** [comment]
Hi, 
I had the same issue. I modified **LogoutRedirectAsync()** in **KeycloakAuthenticationHandler file** with this:

Response.Redirect(
                (await KeycloakIdentity.GenerateLogoutUriAsync(Options, Request.Uri, 
                    new Uri(**Options.PostLogoutRedirectUrl**)))
                    .ToString());

instead of **properties.RedirectUri**

**Comment by dylanplecki** [comment]
Fixed in version 2.1.5 using the proposed fix detailed above.

**Comment by ntheile** [comment]
thx @dylanplecki and @greibach !!!!
